<?php
$objectManagerIn = \Magento\Framework\App\ObjectManager::getInstance();
$priceArr = explode('-', $block->getPriceId());
foreach ($priceArr as $item)
{
    if(is_numeric($item)){
        $pid=$item;
        break;
    }
}
$product = $objectManagerIn->get('Magento\Catalog\Model\ProductFactory')->create()->load($pid);
$priceHelper = $objectManagerIn->create('Magento\Framework\Pricing\Helper\Data'); ?>
<span class="price-container <?= /* @escapeNotVerified */ $block->getAdjustmentCssClasses() ?>"
    <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
<?php if ($block->getDisplayLabel()): ?>
    <span class="price-label"><?= /* @escapeNotVerified */ $block->getDisplayLabel() ?></span>
<?php endif; ?>
    <?php $finalprice =$product->getFinalPrice();
        $finalprice=($finalprice*1); ?>
    <span class="price-label">
<h4>    <b><?php echo $priceHelper->currency($finalprice, true, false);  ?></b>
</h4>
</span>
</span>